### ISSUE TITLE
Create Travis build

### ISSUE THREAD

**Issue by apotterri** [land-of-apps/dagger#1]

**Comment by ta-Bruce** [comment]
Steps to create appmaps:

1. added `appmap.yml `with minimal config required.
2. changed `test_defs.bzl` file to include jvm args for all tests. paths used in the jvm args are absolute paths
3. changed travis build file to run script `bazel query //javatests/... | xargs -n1 bazel run` .

Issues encountered : 

1. `bazel query //javatests/... | xargs -n1 bazel run` is exited with 123 status once executed
2. PR build for appland branch is failing due to json issue in one appmap file.
3. PR builds for versions (2.28.1,2.28.2,2.28.3) are not able to upload appmaps via ruby script.
4. PR builds for oldest versions (2.28, 2.27) are not getting executed due to conflicts with master branch.

All the Branch builds are able to upload appmaps successfully.
